### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by karimeltel** [emkay/material-ui-table-edit#1]
I am getting this error:
ERROR in ./~/material-ui-table-edit/index.jsx
Module parse failed: ...\workspace\cgbs-attributes\web-entry\node_modules\material-ui-table-edit\index.jsx Unexpected token (68:13)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (68:13)

webpack config:

```
loaders: [
  {
    test: /\.jsx?$/,
    loader: 'react-hot!babel',
    exclude: /node_modules/
  },
```

**Comment by karimeltel** [comment]
http://stackoverflow.com/questions/38799364/npm-material-ui-table-edit-loader/38801604#38801604

**Comment by emkay** [comment]
@karimeltel hey I just set this up for my needs. I use browserify with the `reactify` transform. What should probably happen here is that I publish the compiled output so you don't have to worry about that. would that be helpful?

**Comment by karimeltel** [comment]
@emkay It would be really helpful with a small write up on how to use it if possible.  So far I am using this component: http://jsfiddle.net/shoque/eauhzgoL/
However I see that yours is much neater :)
Thank you for your reply!

**Comment by emkay** [comment]
@karimeltel `material-ui-table-edit@3.0.0` should be published with a compiled version. can you give that a try and report back please?

**Comment by emkay** [comment]
@karimeltel tested this out with your webpack config and was able to get a demo page up and working. Let me know if you have any other problems and thanks for using this and reporting the issue. 🙌
