### ISSUE TITLE
Handler for row deletion

### ISSUE THREAD

**Issue by thetrav** [emkay/material-ui-table-edit#12]
So, I can see in the examples there's a toggle to allow deleting rows, however I can't see anything to handle that event.
I was expecting it to either fire an "onChange" event or have a handler that can be passed similar to the onChange param.

If there's a way to do this, please let me know, maybe update the example to cover it, otherwise I'll start working on a PR to add it in.

**Comment by kavimaluskam** [comment]
Sorry @thetrav that i am not quite understanding your questions.
In this example https://raw.githubusercontent.com/emkay/material-ui-table-edit/master/example/table-editor.gif , the toggle is not related to the row deletion. They are just two supported "FieldType" which are separately demonstrated. 

The delete button disappears when you are editing the row, or you can complete disable the delete function by doing sth like 

```javascript
<EditTable
  onChange={onChange}
  rows={rows}
  headerColumns={headers}
  enableDelete={false}
/>
```

Hope that i did not get you wrong. 

Anyway thanks for you contribution!

**Comment by thetrav** [comment]
Toggle was the wrong word to use...

I meant there is a boolean setting for "enableDelete" however I cannot observe an onChange event firing when a row is deleted.
