### ISSUE TITLE
How to paste data from server?

### ISSUE THREAD

**Issue by driversti** [emkay/material-ui-table-edit#2]
How to paste data from callback into rows (see 120-146 strings)?
Here is my code https://gist.github.com/driversti/fa212f2392825f6b1cb036f3d628723a

Sorry for my bad English

**Comment by emkay** [comment]
The data structure you make needs to be something like:

```javascript
var rows = [
  {
    columns: [
      {value: 'something'}
    ]
  }
]
```

For each row you need to specify the column values in the same order as your headers.
