### ISSUE TITLE
Delete a row

### ISSUE THREAD

**Issue by froston** [emkay/material-ui-table-edit#3]

**Comment by emkay** [comment]
There are a couple options.

1. You could somehow handle it yourself and on a render update the rows you are passing in
2. This could be added as a first class feature. 

I'd welcome a PR if you wanted to go the 2 route.

**Comment by Jujunol** [comment]
I too am lacking this functionality

**Comment by emkay** [comment]
@Jujunol if someone wants to add it as a first class feature I am totally ok with adding it and adding people as contributors.
